### ISSUE TITLE
Ask your social media team to create epic reels and add examples to the ReadMe

### ISSUE THREAD

**Issue by drstarson** [Passiolife/Nutrition-AI-Reels#5]
Readme should show Instagram ready reels. They must look good enough to be featured on MindInventory and Passio Media channels. This is the criteria. MindInventory, Mehul, Samar and Passio team should be proud and excited to post the reels created via your work on their social. 

- [x] Create amazing reels using the repo and feature those reels in the ReadMe as examples.
- [x] Remove the current video 

- [x] Check with your social media team to make sure they guide your design choices. They need to be the judges and need to say that reels are looking great enough for them to promote. 

We will need MI and Passio's teams to both share the results of your work on our media channels by the end of the next week, so make sure they look as great as possible and show demos to Sumeet, Sam and your social media team.
